# -*- coding: utf-8 -*-
"""Adder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T92auxa0hEAPbXPuLkulW6NhnCAZNf1d
"""

import pandas as pd
from pandas import ExcelWriter
import os
from google.colab import drive
drive.mount('/content/drive', force_remount=True)
os.chdir('/content/drive/My Drive/VLSI/Hspice/Final/FA/Pre-Sim/output')

col01 = []
col02 = []
col03 = []
col04 = []
col05 = []
col06 = []
col07 = []
col08 = []
col09 = []
col10 = []
col11 = []
col12 = []
col13 = []
col14 = []
col15 = []
col16 = []
col17 = []
col18 = []
col19 = []
col20 = []
col21 = []
col22 = []
col23 = []
col24 = []

col01.append([0])
col02.append([0])
col03.append([0])
col04.append([0])
col05.append([0])
col06.append([0])
col07.append([0])
col08.append([0])
col09.append([0])
col10.append([0])
col11.append([0])
col12.append([0])
col13.append([0])
col14.append([0])
col15.append([0])
col16.append([0])
col17.append([0])
col18.append([0])
col19.append([0])
col20.append([0])
col21.append([0])
col22.append([0])
col23.append([0])
col24.append([0])

with open('stimulus.lis', "r+") as f:
    data = f.readlines()
    
    for line in data:
      word='tr_a_s='
      if(line.strip().find(word)!=-1):
        col01.append(line[len(word)+1:len(word)+12])

      word='tf_a_s='
      if(line.strip().find(word)!=-1):
        col02.append(line[len(word)+1:len(word)+12])

      word='tpdf_a_s='
      if(line.strip().find(word)!=-1):
        col03.append(line[len(word)+1:len(word)+12])

      word='tpdr_a_s='
      if(line.strip().find(word)!=-1):
        col04.append(line[len(word)+1:len(word)+12])

      word='tr_a_cout='
      if(line.strip().find(word)!=-1):
        col05.append(line[len(word)+1:len(word)+12])

      word='tf_a_cout='
      if(line.strip().find(word)!=-1):
        col06.append(line[len(word)+1:len(word)+12])

      word='tpdf_a_cout='
      if(line.strip().find(word)!=-1):
        col07.append(line[len(word)+1:len(word)+12])

      word='tpdr_a_cout='
      if(line.strip().find(word)!=-1):
        col08.append(line[len(word)+1:len(word)+12])

      word='tr_b_s='
      if(line.strip().find(word)!=-1):
        col09.append(line[len(word)+1:len(word)+12])

      word='tf_b_s='
      if(line.strip().find(word)!=-1):
        col10.append(line[len(word)+1:len(word)+12])

      word='tpdf_b_s='
      if(line.strip().find(word)!=-1):
        col11.append(line[len(word)+1:len(word)+12])

      word='tpdr_b_s='
      if(line.strip().find(word)!=-1):
        col12.append(line[len(word)+1:len(word)+12])

      word='tr_b_cout='
      if(line.strip().find(word)!=-1):
        col13.append(line[len(word)+1:len(word)+12])

      word='tf_b_cout='
      if(line.strip().find(word)!=-1):
        col14.append(line[len(word)+1:len(word)+12])

      word='tpdf_b_cout='
      if(line.strip().find(word)!=-1):
        col15.append(line[len(word)+1:len(word)+12])

      word='tpdr_b_cout='
      if(line.strip().find(word)!=-1):
        col16.append(line[len(word)+1:len(word)+12])

      word='tr_cin_s='
      if(line.strip().find(word)!=-1):
        col17.append(line[len(word)+1:len(word)+12])

      word='tf_cin_s='
      if(line.strip().find(word)!=-1):
        col18.append(line[len(word)+1:len(word)+12])

      word='tpdf_cin_s='
      if(line.strip().find(word)!=-1):
        col19.append(line[len(word)+1:len(word)+12])

      word='tpdr_cin_s='
      if(line.strip().find(word)!=-1):
        col20.append(line[len(word)+1:len(word)+12])

      word='tr_cin_cout='
      if(line.strip().find(word)!=-1):
        col21.append(line[len(word)+1:len(word)+12])

      word='tf_cin_cout='
      if(line.strip().find(word)!=-1):
        col22.append(line[len(word)+1:len(word)+12])

      word='tpdf_cin_cout='
      if(line.strip().find(word)!=-1):
        col23.append(line[len(word)+1:len(word)+12])

      word='tpdr_cin_cout='
      if(line.strip().find(word)!=-1):
        col24.append(line[len(word)+1:len(word)+12])


panda = pd.DataFrame(list(zip(col01,col02,col03,col04,col05,col06,col07,col08,col09,
                              col10,col11,col12,col13,col14,col15,col16,col17,col18,
                              col19,col20,col21,col22,col23,col24
                              )),
              columns=['tr_a_s','tf_a_s','tpdf_a_s','tpdr_a_s','tr_a_cout','tf_a_cout','tpdf_a_cout','tpdr_a_cout',
                       'tr_b_s','tf_b_s','tpdf_b_s','tpdr_b_s','tr_b_cout','tf_b_cout','tpdf_b_cout','tpdr_b_cout',
                       'tr_cin_s','tf_cin_s','tpdf_cin_s','tpdr_cin_s','tr_cin_cout','tf_cin_cout','tpdf_cin_cout','tpdr_cin_cout',
              ])



panda_sliced = panda.drop(list([0]))

writer = ExcelWriter('../FA.xlsx')
panda_sliced.to_excel(writer) #can add sheets here if needed
writer.save()

os.chdir('/content/drive/My Drive/VLSI/Hspice/Final/FA/PLS/output')

col01 = []
col02 = []
col03 = []
col04 = []
col05 = []
col06 = []
col07 = []
col08 = []
col09 = []
col10 = []
col11 = []
col12 = []
col13 = []
col14 = []
col15 = []
col16 = []
col17 = []
col18 = []
col19 = []
col20 = []
col21 = []
col22 = []
col23 = []
col24 = []

col01.append([0])
col02.append([0])
col03.append([0])
col04.append([0])
col05.append([0])
col06.append([0])
col07.append([0])
col08.append([0])
col09.append([0])
col10.append([0])
col11.append([0])
col12.append([0])
col13.append([0])
col14.append([0])
col15.append([0])
col16.append([0])
col17.append([0])
col18.append([0])
col19.append([0])
col20.append([0])
col21.append([0])
col22.append([0])
col23.append([0])
col24.append([0])

with open('stimulus.lis', "r+") as f:
    data = f.readlines()
    
    for line in data:
      word='tr_a_s='
      if(line.strip().find(word)!=-1):
        col01.append(line[len(word)+1:len(word)+12])

      word='tf_a_s='
      if(line.strip().find(word)!=-1):
        col02.append(line[len(word)+1:len(word)+12])

      word='tpdf_a_s='
      if(line.strip().find(word)!=-1):
        col03.append(line[len(word)+1:len(word)+12])

      word='tpdr_a_s='
      if(line.strip().find(word)!=-1):
        col04.append(line[len(word)+1:len(word)+12])

      word='tr_a_cout='
      if(line.strip().find(word)!=-1):
        col05.append(line[len(word)+1:len(word)+12])

      word='tf_a_cout='
      if(line.strip().find(word)!=-1):
        col06.append(line[len(word)+1:len(word)+12])

      word='tpdf_a_cout='
      if(line.strip().find(word)!=-1):
        col07.append(line[len(word)+1:len(word)+12])

      word='tpdr_a_cout='
      if(line.strip().find(word)!=-1):
        col08.append(line[len(word)+1:len(word)+12])

      word='tr_b_s='
      if(line.strip().find(word)!=-1):
        col09.append(line[len(word)+1:len(word)+12])

      word='tf_b_s='
      if(line.strip().find(word)!=-1):
        col10.append(line[len(word)+1:len(word)+12])

      word='tpdf_b_s='
      if(line.strip().find(word)!=-1):
        col11.append(line[len(word)+1:len(word)+12])

      word='tpdr_b_s='
      if(line.strip().find(word)!=-1):
        col12.append(line[len(word)+1:len(word)+12])

      word='tr_b_cout='
      if(line.strip().find(word)!=-1):
        col13.append(line[len(word)+1:len(word)+12])

      word='tf_b_cout='
      if(line.strip().find(word)!=-1):
        col14.append(line[len(word)+1:len(word)+12])

      word='tpdf_b_cout='
      if(line.strip().find(word)!=-1):
        col15.append(line[len(word)+1:len(word)+12])

      word='tpdr_b_cout='
      if(line.strip().find(word)!=-1):
        col16.append(line[len(word)+1:len(word)+12])

      word='tr_cin_s='
      if(line.strip().find(word)!=-1):
        col17.append(line[len(word)+1:len(word)+12])

      word='tf_cin_s='
      if(line.strip().find(word)!=-1):
        col18.append(line[len(word)+1:len(word)+12])

      word='tpdf_cin_s='
      if(line.strip().find(word)!=-1):
        col19.append(line[len(word)+1:len(word)+12])

      word='tpdr_cin_s='
      if(line.strip().find(word)!=-1):
        col20.append(line[len(word)+1:len(word)+12])

      word='tr_cin_cout='
      if(line.strip().find(word)!=-1):
        col21.append(line[len(word)+1:len(word)+12])

      word='tf_cin_cout='
      if(line.strip().find(word)!=-1):
        col22.append(line[len(word)+1:len(word)+12])

      word='tpdf_cin_cout='
      if(line.strip().find(word)!=-1):
        col23.append(line[len(word)+1:len(word)+12])

      word='tpdr_cin_cout='
      if(line.strip().find(word)!=-1):
        col24.append(line[len(word)+1:len(word)+12])


panda = pd.DataFrame(list(zip(col01,col02,col03,col04,col05,col06,col07,col08,col09,
                              col10,col11,col12,col13,col14,col15,col16,col17,col18,
                              col19,col20,col21,col22,col23,col24
                              )),
              columns=['tr_a_s','tf_a_s','tpdf_a_s','tpdr_a_s','tr_a_cout','tf_a_cout','tpdf_a_cout','tpdr_a_cout',
                       'tr_b_s','tf_b_s','tpdf_b_s','tpdr_b_s','tr_b_cout','tf_b_cout','tpdf_b_cout','tpdr_b_cout',
                       'tr_cin_s','tf_cin_s','tpdf_cin_s','tpdr_cin_s','tr_cin_cout','tf_cin_cout','tpdf_cin_cout','tpdr_cin_cout',
              ])



panda_sliced = panda.drop(list([0]))

writer = ExcelWriter('../FA_PLS.xlsx')
panda_sliced.to_excel(writer) #can add sheets here if needed
writer.save()

os.chdir('/content/drive/My Drive/VLSI/Hspice/Final/FA_2017/Pre-Sim/output')

col01 = []
col02 = []
col03 = []
col04 = []
col05 = []
col06 = []
col07 = []
col08 = []
col09 = []
col10 = []
col11 = []
col12 = []
col13 = []
col14 = []
col15 = []
col16 = []
col17 = []
col18 = []
col19 = []
col20 = []
col21 = []
col22 = []
col23 = []
col24 = []

col01.append([0])
col02.append([0])
col03.append([0])
col04.append([0])
col05.append([0])
col06.append([0])
col07.append([0])
col08.append([0])
col09.append([0])
col10.append([0])
col11.append([0])
col12.append([0])
col13.append([0])
col14.append([0])
col15.append([0])
col16.append([0])
col17.append([0])
col18.append([0])
col19.append([0])
col20.append([0])
col21.append([0])
col22.append([0])
col23.append([0])
col24.append([0])

with open('stimulus.lis', "r+") as f:
    data = f.readlines()
    
    for line in data:
      word='tr_a_s='
      if(line.strip().find(word)!=-1):
        col01.append(line[len(word)+1:len(word)+12])

      word='tf_a_s='
      if(line.strip().find(word)!=-1):
        col02.append(line[len(word)+1:len(word)+12])

      word='tpdf_a_s='
      if(line.strip().find(word)!=-1):
        col03.append(line[len(word)+1:len(word)+12])

      word='tpdr_a_s='
      if(line.strip().find(word)!=-1):
        col04.append(line[len(word)+1:len(word)+12])

      word='tr_a_cout='
      if(line.strip().find(word)!=-1):
        col05.append(line[len(word)+1:len(word)+12])

      word='tf_a_cout='
      if(line.strip().find(word)!=-1):
        col06.append(line[len(word)+1:len(word)+12])

      word='tpdf_a_cout='
      if(line.strip().find(word)!=-1):
        col07.append(line[len(word)+1:len(word)+12])

      word='tpdr_a_cout='
      if(line.strip().find(word)!=-1):
        col08.append(line[len(word)+1:len(word)+12])

      word='tr_b_s='
      if(line.strip().find(word)!=-1):
        col09.append(line[len(word)+1:len(word)+12])

      word='tf_b_s='
      if(line.strip().find(word)!=-1):
        col10.append(line[len(word)+1:len(word)+12])

      word='tpdf_b_s='
      if(line.strip().find(word)!=-1):
        col11.append(line[len(word)+1:len(word)+12])

      word='tpdr_b_s='
      if(line.strip().find(word)!=-1):
        col12.append(line[len(word)+1:len(word)+12])

      word='tr_b_cout='
      if(line.strip().find(word)!=-1):
        col13.append(line[len(word)+1:len(word)+12])

      word='tf_b_cout='
      if(line.strip().find(word)!=-1):
        col14.append(line[len(word)+1:len(word)+12])

      word='tpdf_b_cout='
      if(line.strip().find(word)!=-1):
        col15.append(line[len(word)+1:len(word)+12])

      word='tpdr_b_cout='
      if(line.strip().find(word)!=-1):
        col16.append(line[len(word)+1:len(word)+12])

      word='tr_cin_s='
      if(line.strip().find(word)!=-1):
        col17.append(line[len(word)+1:len(word)+12])

      word='tf_cin_s='
      if(line.strip().find(word)!=-1):
        col18.append(line[len(word)+1:len(word)+12])

      word='tpdf_cin_s='
      if(line.strip().find(word)!=-1):
        col19.append(line[len(word)+1:len(word)+12])

      word='tpdr_cin_s='
      if(line.strip().find(word)!=-1):
        col20.append(line[len(word)+1:len(word)+12])

      word='tr_cin_cout='
      if(line.strip().find(word)!=-1):
        col21.append(line[len(word)+1:len(word)+12])

      word='tf_cin_cout='
      if(line.strip().find(word)!=-1):
        col22.append(line[len(word)+1:len(word)+12])

      word='tpdf_cin_cout='
      if(line.strip().find(word)!=-1):
        col23.append(line[len(word)+1:len(word)+12])

      word='tpdr_cin_cout='
      if(line.strip().find(word)!=-1):
        col24.append(line[len(word)+1:len(word)+12])


panda = pd.DataFrame(list(zip(col01,col02,col03,col04,col05,col06,col07,col08,col09,
                              col10,col11,col12,col13,col14,col15,col16,col17,col18,
                              col19,col20,col21,col22,col23,col24
                              )),
              columns=['tr_a_s','tf_a_s','tpdf_a_s','tpdr_a_s','tr_a_cout','tf_a_cout','tpdf_a_cout','tpdr_a_cout',
                       'tr_b_s','tf_b_s','tpdf_b_s','tpdr_b_s','tr_b_cout','tf_b_cout','tpdf_b_cout','tpdr_b_cout',
                       'tr_cin_s','tf_cin_s','tpdf_cin_s','tpdr_cin_s','tr_cin_cout','tf_cin_cout','tpdf_cin_cout','tpdr_cin_cout',
              ])



panda_sliced = panda.drop(list([0]))

writer = ExcelWriter('../FA_2017.xlsx')
panda_sliced.to_excel(writer) #can add sheets here if needed
writer.save()

os.chdir('/content/drive/My Drive/VLSI/Hspice/Final/FA_2017/PLS/output')

col01 = []
col02 = []
col03 = []
col04 = []
col05 = []
col06 = []
col07 = []
col08 = []
col09 = []
col10 = []
col11 = []
col12 = []
col13 = []
col14 = []
col15 = []
col16 = []
col17 = []
col18 = []
col19 = []
col20 = []
col21 = []
col22 = []
col23 = []
col24 = []

col01.append([0])
col02.append([0])
col03.append([0])
col04.append([0])
col05.append([0])
col06.append([0])
col07.append([0])
col08.append([0])
col09.append([0])
col10.append([0])
col11.append([0])
col12.append([0])
col13.append([0])
col14.append([0])
col15.append([0])
col16.append([0])
col17.append([0])
col18.append([0])
col19.append([0])
col20.append([0])
col21.append([0])
col22.append([0])
col23.append([0])
col24.append([0])

with open('stimulus.lis', "r+") as f:
    data = f.readlines()
    
    for line in data:
      word='tr_a_s='
      if(line.strip().find(word)!=-1):
        col01.append(line[len(word)+1:len(word)+12])

      word='tf_a_s='
      if(line.strip().find(word)!=-1):
        col02.append(line[len(word)+1:len(word)+12])

      word='tpdf_a_s='
      if(line.strip().find(word)!=-1):
        col03.append(line[len(word)+1:len(word)+12])

      word='tpdr_a_s='
      if(line.strip().find(word)!=-1):
        col04.append(line[len(word)+1:len(word)+12])

      word='tr_a_cout='
      if(line.strip().find(word)!=-1):
        col05.append(line[len(word)+1:len(word)+12])

      word='tf_a_cout='
      if(line.strip().find(word)!=-1):
        col06.append(line[len(word)+1:len(word)+12])

      word='tpdf_a_cout='
      if(line.strip().find(word)!=-1):
        col07.append(line[len(word)+1:len(word)+12])

      word='tpdr_a_cout='
      if(line.strip().find(word)!=-1):
        col08.append(line[len(word)+1:len(word)+12])

      word='tr_b_s='
      if(line.strip().find(word)!=-1):
        col09.append(line[len(word)+1:len(word)+12])

      word='tf_b_s='
      if(line.strip().find(word)!=-1):
        col10.append(line[len(word)+1:len(word)+12])

      word='tpdf_b_s='
      if(line.strip().find(word)!=-1):
        col11.append(line[len(word)+1:len(word)+12])

      word='tpdr_b_s='
      if(line.strip().find(word)!=-1):
        col12.append(line[len(word)+1:len(word)+12])

      word='tr_b_cout='
      if(line.strip().find(word)!=-1):
        col13.append(line[len(word)+1:len(word)+12])

      word='tf_b_cout='
      if(line.strip().find(word)!=-1):
        col14.append(line[len(word)+1:len(word)+12])

      word='tpdf_b_cout='
      if(line.strip().find(word)!=-1):
        col15.append(line[len(word)+1:len(word)+12])

      word='tpdr_b_cout='
      if(line.strip().find(word)!=-1):
        col16.append(line[len(word)+1:len(word)+12])

      word='tr_cin_s='
      if(line.strip().find(word)!=-1):
        col17.append(line[len(word)+1:len(word)+12])

      word='tf_cin_s='
      if(line.strip().find(word)!=-1):
        col18.append(line[len(word)+1:len(word)+12])

      word='tpdf_cin_s='
      if(line.strip().find(word)!=-1):
        col19.append(line[len(word)+1:len(word)+12])

      word='tpdr_cin_s='
      if(line.strip().find(word)!=-1):
        col20.append(line[len(word)+1:len(word)+12])

      word='tr_cin_cout='
      if(line.strip().find(word)!=-1):
        col21.append(line[len(word)+1:len(word)+12])

      word='tf_cin_cout='
      if(line.strip().find(word)!=-1):
        col22.append(line[len(word)+1:len(word)+12])

      word='tpdf_cin_cout='
      if(line.strip().find(word)!=-1):
        col23.append(line[len(word)+1:len(word)+12])

      word='tpdr_cin_cout='
      if(line.strip().find(word)!=-1):
        col24.append(line[len(word)+1:len(word)+12])


panda = pd.DataFrame(list(zip(col01,col02,col03,col04,col05,col06,col07,col08,col09,
                              col10,col11,col12,col13,col14,col15,col16,col17,col18,
                              col19,col20,col21,col22,col23,col24
                              )),
              columns=['tr_a_s','tf_a_s','tpdf_a_s','tpdr_a_s','tr_a_cout','tf_a_cout','tpdf_a_cout','tpdr_a_cout',
                       'tr_b_s','tf_b_s','tpdf_b_s','tpdr_b_s','tr_b_cout','tf_b_cout','tpdf_b_cout','tpdr_b_cout',
                       'tr_cin_s','tf_cin_s','tpdf_cin_s','tpdr_cin_s','tr_cin_cout','tf_cin_cout','tpdf_cin_cout','tpdr_cin_cout',
              ])



panda_sliced = panda.drop(list([0]))

writer = ExcelWriter('../FA_2017_PLS.xlsx')
panda_sliced.to_excel(writer) #can add sheets here if needed
writer.save()

os.chdir('/content/drive/My Drive/VLSI/Hspice/Final/TGFA_2010/Pre-Sim/output')

col01 = []
col02 = []
col03 = []
col04 = []
col05 = []
col06 = []
col07 = []
col08 = []
col09 = []
col10 = []
col11 = []
col12 = []
col13 = []
col14 = []
col15 = []
col16 = []
col17 = []
col18 = []
col19 = []
col20 = []
col21 = []
col22 = []
col23 = []
col24 = []

col01.append([0])
col02.append([0])
col03.append([0])
col04.append([0])
col05.append([0])
col06.append([0])
col07.append([0])
col08.append([0])
col09.append([0])
col10.append([0])
col11.append([0])
col12.append([0])
col13.append([0])
col14.append([0])
col15.append([0])
col16.append([0])
col17.append([0])
col18.append([0])
col19.append([0])
col20.append([0])
col21.append([0])
col22.append([0])
col23.append([0])
col24.append([0])

with open('stimulus.lis', "r+") as f:
    data = f.readlines()
    
    for line in data:
      word='tr_a_s='
      if(line.strip().find(word)!=-1):
        col01.append(line[len(word)+1:len(word)+12])

      word='tf_a_s='
      if(line.strip().find(word)!=-1):
        col02.append(line[len(word)+1:len(word)+12])

      word='tpdf_a_s='
      if(line.strip().find(word)!=-1):
        col03.append(line[len(word)+1:len(word)+12])

      word='tpdr_a_s='
      if(line.strip().find(word)!=-1):
        col04.append(line[len(word)+1:len(word)+12])

      word='tr_a_cout='
      if(line.strip().find(word)!=-1):
        col05.append(line[len(word)+1:len(word)+12])

      word='tf_a_cout='
      if(line.strip().find(word)!=-1):
        col06.append(line[len(word)+1:len(word)+12])

      word='tpdf_a_cout='
      if(line.strip().find(word)!=-1):
        col07.append(line[len(word)+1:len(word)+12])

      word='tpdr_a_cout='
      if(line.strip().find(word)!=-1):
        col08.append(line[len(word)+1:len(word)+12])

      word='tr_b_s='
      if(line.strip().find(word)!=-1):
        col09.append(line[len(word)+1:len(word)+12])

      word='tf_b_s='
      if(line.strip().find(word)!=-1):
        col10.append(line[len(word)+1:len(word)+12])

      word='tpdf_b_s='
      if(line.strip().find(word)!=-1):
        col11.append(line[len(word)+1:len(word)+12])

      word='tpdr_b_s='
      if(line.strip().find(word)!=-1):
        col12.append(line[len(word)+1:len(word)+12])

      word='tr_b_cout='
      if(line.strip().find(word)!=-1):
        col13.append(line[len(word)+1:len(word)+12])

      word='tf_b_cout='
      if(line.strip().find(word)!=-1):
        col14.append(line[len(word)+1:len(word)+12])

      word='tpdf_b_cout='
      if(line.strip().find(word)!=-1):
        col15.append(line[len(word)+1:len(word)+12])

      word='tpdr_b_cout='
      if(line.strip().find(word)!=-1):
        col16.append(line[len(word)+1:len(word)+12])

      word='tr_cin_s='
      if(line.strip().find(word)!=-1):
        col17.append(line[len(word)+1:len(word)+12])

      word='tf_cin_s='
      if(line.strip().find(word)!=-1):
        col18.append(line[len(word)+1:len(word)+12])

      word='tpdf_cin_s='
      if(line.strip().find(word)!=-1):
        col19.append(line[len(word)+1:len(word)+12])

      word='tpdr_cin_s='
      if(line.strip().find(word)!=-1):
        col20.append(line[len(word)+1:len(word)+12])

      word='tr_cin_cout='
      if(line.strip().find(word)!=-1):
        col21.append(line[len(word)+1:len(word)+12])

      word='tf_cin_cout='
      if(line.strip().find(word)!=-1):
        col22.append(line[len(word)+1:len(word)+12])

      word='tpdf_cin_cout='
      if(line.strip().find(word)!=-1):
        col23.append(line[len(word)+1:len(word)+12])

      word='tpdr_cin_cout='
      if(line.strip().find(word)!=-1):
        col24.append(line[len(word)+1:len(word)+12])


panda = pd.DataFrame(list(zip(col01,col02,col03,col04,col05,col06,col07,col08,col09,
                              col10,col11,col12,col13,col14,col15,col16,col17,col18,
                              col19,col20,col21,col22,col23,col24
                              )),
              columns=['tr_a_s','tf_a_s','tpdf_a_s','tpdr_a_s','tr_a_cout','tf_a_cout','tpdf_a_cout','tpdr_a_cout',
                       'tr_b_s','tf_b_s','tpdf_b_s','tpdr_b_s','tr_b_cout','tf_b_cout','tpdf_b_cout','tpdr_b_cout',
                       'tr_cin_s','tf_cin_s','tpdf_cin_s','tpdr_cin_s','tr_cin_cout','tf_cin_cout','tpdf_cin_cout','tpdr_cin_cout',
              ])



panda_sliced = panda.drop(list([0]))

writer = ExcelWriter('../TGFA_2010.xlsx')
panda_sliced.to_excel(writer) #can add sheets here if needed
writer.save()

os.chdir('/content/drive/My Drive/VLSI/Hspice/Final/TGFA_2010/PLS/output')

col01 = []
col02 = []
col03 = []
col04 = []
col05 = []
col06 = []
col07 = []
col08 = []
col09 = []
col10 = []
col11 = []
col12 = []
col13 = []
col14 = []
col15 = []
col16 = []
col17 = []
col18 = []
col19 = []
col20 = []
col21 = []
col22 = []
col23 = []
col24 = []

col01.append([0])
col02.append([0])
col03.append([0])
col04.append([0])
col05.append([0])
col06.append([0])
col07.append([0])
col08.append([0])
col09.append([0])
col10.append([0])
col11.append([0])
col12.append([0])
col13.append([0])
col14.append([0])
col15.append([0])
col16.append([0])
col17.append([0])
col18.append([0])
col19.append([0])
col20.append([0])
col21.append([0])
col22.append([0])
col23.append([0])
col24.append([0])

with open('stimulus.lis', "r+") as f:
    data = f.readlines()
    
    for line in data:
      word='tr_a_s='
      if(line.strip().find(word)!=-1):
        col01.append(line[len(word)+1:len(word)+12])

      word='tf_a_s='
      if(line.strip().find(word)!=-1):
        col02.append(line[len(word)+1:len(word)+12])

      word='tpdf_a_s='
      if(line.strip().find(word)!=-1):
        col03.append(line[len(word)+1:len(word)+12])

      word='tpdr_a_s='
      if(line.strip().find(word)!=-1):
        col04.append(line[len(word)+1:len(word)+12])

      word='tr_a_cout='
      if(line.strip().find(word)!=-1):
        col05.append(line[len(word)+1:len(word)+12])

      word='tf_a_cout='
      if(line.strip().find(word)!=-1):
        col06.append(line[len(word)+1:len(word)+12])

      word='tpdf_a_cout='
      if(line.strip().find(word)!=-1):
        col07.append(line[len(word)+1:len(word)+12])

      word='tpdr_a_cout='
      if(line.strip().find(word)!=-1):
        col08.append(line[len(word)+1:len(word)+12])

      word='tr_b_s='
      if(line.strip().find(word)!=-1):
        col09.append(line[len(word)+1:len(word)+12])

      word='tf_b_s='
      if(line.strip().find(word)!=-1):
        col10.append(line[len(word)+1:len(word)+12])

      word='tpdf_b_s='
      if(line.strip().find(word)!=-1):
        col11.append(line[len(word)+1:len(word)+12])

      word='tpdr_b_s='
      if(line.strip().find(word)!=-1):
        col12.append(line[len(word)+1:len(word)+12])

      word='tr_b_cout='
      if(line.strip().find(word)!=-1):
        col13.append(line[len(word)+1:len(word)+12])

      word='tf_b_cout='
      if(line.strip().find(word)!=-1):
        col14.append(line[len(word)+1:len(word)+12])

      word='tpdf_b_cout='
      if(line.strip().find(word)!=-1):
        col15.append(line[len(word)+1:len(word)+12])

      word='tpdr_b_cout='
      if(line.strip().find(word)!=-1):
        col16.append(line[len(word)+1:len(word)+12])

      word='tr_cin_s='
      if(line.strip().find(word)!=-1):
        col17.append(line[len(word)+1:len(word)+12])

      word='tf_cin_s='
      if(line.strip().find(word)!=-1):
        col18.append(line[len(word)+1:len(word)+12])

      word='tpdf_cin_s='
      if(line.strip().find(word)!=-1):
        col19.append(line[len(word)+1:len(word)+12])

      word='tpdr_cin_s='
      if(line.strip().find(word)!=-1):
        col20.append(line[len(word)+1:len(word)+12])

      word='tr_cin_cout='
      if(line.strip().find(word)!=-1):
        col21.append(line[len(word)+1:len(word)+12])

      word='tf_cin_cout='
      if(line.strip().find(word)!=-1):
        col22.append(line[len(word)+1:len(word)+12])

      word='tpdf_cin_cout='
      if(line.strip().find(word)!=-1):
        col23.append(line[len(word)+1:len(word)+12])

      word='tpdr_cin_cout='
      if(line.strip().find(word)!=-1):
        col24.append(line[len(word)+1:len(word)+12])


panda = pd.DataFrame(list(zip(col01,col02,col03,col04,col05,col06,col07,col08,col09,
                              col10,col11,col12,col13,col14,col15,col16,col17,col18,
                              col19,col20,col21,col22,col23,col24
                              )),
              columns=['tr_a_s','tf_a_s','tpdf_a_s','tpdr_a_s','tr_a_cout','tf_a_cout','tpdf_a_cout','tpdr_a_cout',
                       'tr_b_s','tf_b_s','tpdf_b_s','tpdr_b_s','tr_b_cout','tf_b_cout','tpdf_b_cout','tpdr_b_cout',
                       'tr_cin_s','tf_cin_s','tpdf_cin_s','tpdr_cin_s','tr_cin_cout','tf_cin_cout','tpdf_cin_cout','tpdr_cin_cout',
              ])



panda_sliced = panda.drop(list([0]))

writer = ExcelWriter('../TGFA_2010_PLS.xlsx')
panda_sliced.to_excel(writer) #can add sheets here if needed
writer.save()