# -*- coding: utf-8 -*-
"""nor2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nm5jD7oSuOdhiGz55UFhvXBQ5FB1Sx6v
"""

import pandas as pd
from pandas import ExcelWriter
import os
from google.colab import drive
drive.mount('/content/drive', force_remount=True)
os.chdir('/content/drive/My Drive/vlsi/Hspice/nor2/Pre-Sim/output')

col01 = []
col02 = []
col03 = []
col04 = []
col05 = []
col06 = []
col07 = []
col08 = []
col09 = []

col01.append([0])
col02.append([0])
col03.append([0])
col04.append([0])
col05.append([0])
col06.append([0])
col07.append([0])
col08.append([0])
col09.append([0])

with open('stimulus.lis', "r+") as f:
    data = f.readlines()
    
    for line in data:
      word='tpdf='
      if(line.strip().find(word)!=-1):
        col01.append(line[len(word)+1:len(word)+12])

      word='tpdr='
      if(line.strip().find(word)!=-1):
        col02.append(line[len(word)+1:len(word)+12])

      word='tpd='
      if(line.strip().find(word)!=-1):
        col03.append(line[len(word)+1:len(word)+12])

      word='tcdf='
      if(line.strip().find(word)!=-1):
        col04.append(line[len(word)+1:len(word)+12])

      word='tcd='
      if(line.strip().find(word)!=-1):
        col05.append(line[len(word)+1:len(word)+12])

      word='tr='
      if(line.strip().find(word)!=-1):
        col06.append(line[len(word)+1:len(word)+12])

      word='tf='
      if(line.strip().find(word)!=-1):
        col07.append(line[len(word)+1:len(word)+12])

      word='avgpower='
      if(line.strip().find(word)!=-1):
        col08.append(line[len(word)+1:len(word)+12])

      word='peakpower='
      if(line.strip().find(word)!=-1):
        col09.append(line[len(word)+1:len(word)+12])


panda = pd.DataFrame(list(zip(col01,col02,col03,col04,col05,col06,col07,col08,col09)),
              columns=['tpdf','tpdr','tpd','tcdf','tcd','tr','tf','avgpower','peakpower'])
panda_sliced = panda.drop(list([0]))

writer = ExcelWriter('../nor2_Pre-Sim.xlsx')
panda_sliced.to_excel(writer) #can add sheets here if needed
writer.save()

os.chdir('/content/drive/My Drive/vlsi/Hspice/nor2/PLS/output')

col01 = []
col02 = []
col03 = []
col04 = []
col05 = []
col06 = []
col07 = []
col08 = []
col09 = []

col01.append([0])
col02.append([0])
col03.append([0])
col04.append([0])
col05.append([0])
col06.append([0])
col07.append([0])
col08.append([0])
col09.append([0])

with open('stimulus.lis', "r+") as f:
    data = f.readlines()
    
    for line in data:
      word='tpdf='
      if(line.strip().find(word)!=-1):
        col01.append(line[len(word)+1:len(word)+12])

      word='tpdr='
      if(line.strip().find(word)!=-1):
        col02.append(line[len(word)+1:len(word)+12])

      word='tpd='
      if(line.strip().find(word)!=-1):
        col03.append(line[len(word)+1:len(word)+12])

      word='tcdf='
      if(line.strip().find(word)!=-1):
        col04.append(line[len(word)+1:len(word)+12])

      word='tcd='
      if(line.strip().find(word)!=-1):
        col05.append(line[len(word)+1:len(word)+12])

      word='tr='
      if(line.strip().find(word)!=-1):
        col06.append(line[len(word)+1:len(word)+12])

      word='tf='
      if(line.strip().find(word)!=-1):
        col07.append(line[len(word)+1:len(word)+12])

      word='avgpower='
      if(line.strip().find(word)!=-1):
        col08.append(line[len(word)+1:len(word)+12])

      word='peakpower='
      if(line.strip().find(word)!=-1):
        col09.append(line[len(word)+1:len(word)+12])


panda = pd.DataFrame(list(zip(col01,col02,col03,col04,col05,col06,col07,col08,col09)),
              columns=['tpdf','tpdr','tpd','tcdf','tcd','tr','tf','avgpower','peakpower'])
panda_sliced = panda.drop(list([0]))

writer = ExcelWriter('../nor2_PLS.xlsx')
panda_sliced.to_excel(writer) #can add sheets here if needed
writer.save()